
const IMG={
  loki:"https://image.gcores.com/39010183-7657-4996-80cf-650ed3fb663a.jpg?x-oss-process=image%2Fresize%2Climit_1%2Cm_mfit%2Cw_2000%2Fquality%2Cq_90%2Fformat%2Cwebp%2Fbright%2C-20",
};
const data=[
{id:"f405",title:"Fantastic Four (2005)",year:"2005",type:"movie",route:"Victor von Doom",priority:5,icon:"🧪",theme:"r",poster:"assets/posters/01.jpg",source:"https://www.impawards.com/2005/fantastic_four.html",why:"Comprender a Victor von Doom como científico, su relación con Reed Richards y el origen de su rivalidad.",before:["Fantastic Four (ninguno obligatorio)"],learn:["Victor von Doom","Reed Richards","Latveria","Rivalidad Doom–Reed","Ciencia de Doom"],connections:["Victor von Doom","Reed Richards","Fantastic Four"],unlocks:["Victor von Doom","Reed Richards","Latveria"],next:"Fantastic Four: Rise of the Silver Surfer",runtime:106},
{id:"f407",title:"Fantastic Four: Rise of the Silver Surfer",year:"2007",type:"movie",route:"Fantastic Four",priority:4,icon:"🌌",theme:"p",poster:"assets/posters/02.jpg",source:"https://www.imdb.com/title/tt0486576/mediaviewer/rm3011649024",why:"Amplía el alcance de Doom hacia el poder cósmico y muestra cuánto está dispuesto a arriesgar por obtenerlo.",before:["Fantastic Four (2005)"],learn:["Ambición de Doom","Poder cósmico","Silver Surfer","Escala de amenaza"],connections:["Doom","Poder cósmico","Fantastic Four"],unlocks:["Poder cósmico"],next:"The Fantastic Four: First Steps",runtime:92},
{id:"first",title:"The Fantastic Four: First Steps",year:"2025 · MCU",type:"movie",route:"Fantastic Four",priority:5,icon:"🚀",theme:"b",poster:"assets/posters/03.jpg",source:"https://press.disney.co.uk/gallery/the-fantastic-four-first-steps-logos-and-images",why:"Establece la nueva continuidad de Fantastic Four dentro del MCU y es una pieza clave para entender el contexto de Doom en la nueva etapa.",before:["Ninguno obligatorio"],learn:["Nuevo Fantastic Four","MCU","Reed Richards","Sue Storm","Conexiones futuras"],connections:["Fantastic Four","MCU","Doom"],unlocks:["Fantastic Four"],next:"Fantastic Four: World's Greatest Heroes — episodios clave",runtime:114},
{id:"mask",title:"Fantastic Four (1994) — The Mask of Doom",year:"T1:E8–E10",type:"episode",route:"Victor von Doom",priority:5,icon:"🦾",theme:"",poster:"assets/posters/14.jpg",source:"https://en.wikipedia.org/wiki/Fantastic_Four_(1994_TV_series)",why:"Profundiza en el pasado de Victor, su relación con Reed y su papel como amenaza intelectual.",before:["Ninguno obligatorio"],learn:["Pasado de Victor","Doom–Reed","Latveria","Doom como estratega"],connections:["Victor","Reed","Latveria"],unlocks:["Historia de Victor"],next:"World's Greatest Heroes — episodios clave",runtime:66},
{id:"wgh",title:"Fantastic Four: World's Greatest Heroes — episodios clave",year:"T1:E3, E12, E14, E25",type:"episode",route:"Victor von Doom",priority:5,icon:"👑",theme:"",poster:"assets/posters/04.jpg",source:"https://en.wikipedia.org/wiki/Fantastic_Four:_World%27s_Greatest_Heroes",why:"Construye una visión más amplia de Doom: inteligencia, Doombots, Latveria y estrategia.",before:["Fantastic Four"],learn:["Doombots","Latveria","Superioridad intelectual","Estrategia"],connections:["Doom","Doombots","Latveria"],unlocks:["Doombots"],next:"The Avengers: Earth's Mightiest Heroes",runtime:88},
{id:"aemh",title:"The Avengers: Earth's Mightiest Heroes — The Private War of Doctor Doom",year:"T2:E1",type:"episode",route:"Avengers",priority:4,icon:"⚔️",theme:"",poster:"assets/posters/05.jpeg",source:"https://en.wikipedia.org/wiki/The_Avengers:_Earth%27s_Mightiest_Heroes",why:"Doom deja de ser únicamente un problema de Fantastic Four y pasa a representar una amenaza para Avengers.",before:["Conocer a Doom y Fantastic Four"],learn:["Doom vs Avengers","Escala de amenaza","Estrategia","Tecnología"],connections:["Doom","Avengers"],unlocks:["Avengers"],next:"Spider-Man (1994) — Secret Wars",runtime:22},
{id:"secret",title:"Spider-Man (1994) — Secret Wars",year:"T5:E9–E11",type:"episode",route:"Multiverse",priority:5,icon:"🌀",theme:"p",poster:"assets/posters/06.jpg",source:"https://en.wikipedia.org/wiki/Spider-Man_(1994_TV_series)",why:"Introduce a Doom frente a poderes capaces de alterar la realidad y conecta directamente con el concepto de Secret Wars.",before:["Doom como amenaza","Fantastic Four"],learn:["Beyonder","Doom obtiene poder","Realidad alterada","Secret Wars","Battleworld"],connections:["Beyonder","Doom","Battleworld","Secret Wars"],unlocks:["Beyonder","Battleworld","Secret Wars"],next:"Loki",runtime:66},
{id:"loki",title:"Loki — temporadas 1 y 2",year:"T1–T2",type:"series",route:"Multiverse",priority:4,icon:"⏳",theme:"p",poster:"assets/posters/07.jpg",source:"https://www.marvel.com/tv-shows/loki/1",why:"Construye la gramática del multiverso, las ramas temporales y las consecuencias de manipular la estructura de la realidad.",before:["MCU básico recomendado"],learn:["Ramas temporales","TVA","Multiverso","Consecuencias"],connections:["Multiverse","TVA","Tiempo"],unlocks:["Multiverse"],next:"Doctor Strange in the Multiverse of Madness",runtime:660},
{id:"strange",title:"Doctor Strange in the Multiverse of Madness",year:"2022",type:"movie",route:"Multiverse",priority:4,icon:"🪄",theme:"p",poster:"assets/posters/08.jpg",source:"https://www.marvel.com/articles/movies/doctor-strange-multiverse-of-madness-character-posters",why:"Introduce de forma explícita realidades alternativas e incursiones, conceptos esenciales para la preparación multiversal.",before:["Doctor Strange recomendado","Loki recomendado"],learn:["Incursiones","Realidades alternativas","Amenaza multiversal"],connections:["Multiverse","Incursions"],unlocks:["Incursions"],next:"Spider-Man: No Way Home",runtime:126},
{id:"nwh",title:"Spider-Man: No Way Home",year:"2021",type:"movie",route:"Connections",priority:4,icon:"🕷️",theme:"b",poster:"assets/posters/09.jpg",source:"https://en.wikipedia.org/wiki/Spider-Man:_No_Way_Home",why:"Refuerza la idea de variantes y cruces entre realidades.",before:["Spider-Man MCU recomendado"],learn:["Variantes","Cruce de universos"],connections:["Multiverse","Variants"],unlocks:["Variants"],next:"Deadpool & Wolverine",runtime:148},
{id:"deadpool",title:"Deadpool & Wolverine",year:"2024",type:"movie",route:"Connections",priority:4,icon:"⚔️",theme:"r",poster:"assets/posters/10.jpg",source:"https://en.wikipedia.org/wiki/Deadpool_%26_Wolverine",why:"Conecta el legado Fox con el MCU y amplía el panorama de realidades y personajes.",before:["X-Men recomendado"],learn:["Legado Fox","X-Men","Multiverso conectado"],connections:["X-Men","Fox","Multiverse"],unlocks:["X-Men"],next:"Avengers: Infinity War",runtime:128},
{id:"iw",title:"Avengers: Infinity War",year:"2018",type:"movie",route:"Final",priority:3,icon:"💥",theme:"r",poster:"assets/posters/11.jpg",source:"https://en.wikipedia.org/wiki/Avengers:_Infinity_War",why:"Establece el estado del MCU y las consecuencias de Thanos que condicionan la etapa posterior.",before:["Avengers previas recomendadas"],learn:["Estado del MCU","Thanos","Consecuencias"],connections:["Avengers","MCU"],unlocks:[],next:"Avengers: Endgame",runtime:149},
{id:"eg",title:"Avengers: Endgame",year:"2019",type:"movie",route:"Final",priority:4,icon:"⏱️",theme:"y",poster:"assets/posters/12.jpg",source:"https://en.wikipedia.org/wiki/Avengers:_Endgame",why:"Cierra una era del MCU y establece las consecuencias que llevan a la nueva generación.",before:["Infinity War"],learn:["Consecuencias del Blip","Nueva generación","Estado del MCU"],connections:["Avengers","MCU","Time"],unlocks:[],next:null,runtime:181}

{id:"ff94",title:"Fantastic Four (1994)",year:"1994–1996",type:"series",route:"Victor von Doom",priority:5,icon:"🧬",theme:"r",poster:"assets/posters/13.jpg",source:"https://en.wikipedia.org/wiki/Fantastic_Four_(1994_TV_series)",why:"Presenta una versión animada de Victor, su relación con Reed y el universo clásico de Fantastic Four.",before:["Fantastic Four (2005) recomendado"],learn:["Victor clásico","Doom–Reed","Latveria","Fantastic Four"],connections:["Victor von Doom","Reed Richards","Latveria","Fantastic Four"],unlocks:["Victor clásico"],next:"The Mask of Doom",runtime:44},
{id:"secretDoom",title:"Spider-Man (1994) — Secret Wars: Doom Focus",year:"T5:E9–E11",type:"episode",route:"Battleworld",priority:5,icon:"🌀",theme:"p",poster:"assets/posters/15.jpg",source:"https://en.wikipedia.org/wiki/Spider-Man_(1994_TV_series)",why:"Profundiza en el papel de Doom dentro de Secret Wars: su ambición, su estrategia y su intento de apropiarse de un poder superior.",before:["Spider-Man — Secret Wars"],learn:["Doom en Battleworld","Beyonder","Poder absoluto","Estrategia de Doom"],connections:["Doom","Beyonder","Battleworld","Secret Wars"],unlocks:["Doom en Battleworld","Poder absoluto"],next:"The Incredible Hulk — Doom",runtime:66},
{id:"hulkDoom",title:"The Incredible Hulk (1996) — Doom",year:"1996",type:"episode",route:"Victor von Doom",priority:3,icon:"💚",theme:"r",poster:"assets/posters/16.jpg",source:"https://en.wikipedia.org/wiki/The_Incredible_Hulk_(1996_TV_series)",why:"Muestra a Doom enfrentándose a otro héroe Marvel y amplía la percepción de su amenaza más allá de Fantastic Four.",before:["Conocer a Doom"],learn:["Doom vs Hulk","Poder tecnológico","Amenaza individual"],connections:["Doom","Hulk","Technology"],unlocks:["Doom vs Hulk"],next:"Iron Man: Armored Adventures — Doctor Doom",runtime:22},
{id:"ironDoom",title:"Iron Man: Armored Adventures — Doctor Doom",year:"2009–2012",type:"series",route:"Technology",priority:3,icon:"🤖",theme:"b",poster:"assets/posters/17.jpg",source:"https://en.wikipedia.org/wiki/Iron_Man:_Armored_Adventures",why:"Permite comparar la inteligencia tecnológica de Doom con la de Tony Stark y observar otra interpretación juvenil del personaje.",before:["Doom como científico"],learn:["Doom vs Iron Man","Tecnología","Armadura","Inteligencia"],connections:["Doom","Iron Man","Technology"],unlocks:["Doom vs Iron Man"],next:"The Super Hero Squad Show — Doctor Doom",runtime:44},
{id:"squadDoom",title:"The Super Hero Squad Show — Doctor Doom",year:"2009–2011",type:"series",route:"Animation",priority:2,icon:"🎭",theme:"p",poster:"assets/posters/18.jpg",source:"https://en.wikipedia.org/wiki/The_Super_Hero_Squad_Show",why:"Presenta una versión cómica de Doom y ayuda a distinguir los rasgos esenciales del personaje de sus reinterpretaciones.",before:["Ninguno obligatorio"],learn:["Doom caricaturesco","Rasgos esenciales","Doombots","Humor"],connections:["Doom","Doombots","Animation"],unlocks:["Doom en animación"],next:"The Private War of Doctor Doom — Deep Dive",runtime:22},
{id:"aemhDeep",title:"The Avengers: Earth's Mightiest Heroes — The Private War of Doctor Doom: Deep Dive",year:"T2:E1",type:"episode",route:"Avengers",priority:5,icon:"⚔️",theme:"",poster:"assets/posters/19.jpg",source:"https://en.wikipedia.org/wiki/The_Avengers:_Earth%27s_Mightiest_Heroes",why:"Revisa a Doom como amenaza geopolítica y tecnológica capaz de poner en jaque a un equipo completo de Avengers.",before:["The Private War of Doctor Doom"],learn:["Latveria","Doom vs Avengers","Tecnología","Geopolítica"],connections:["Doom","Avengers","Latveria"],unlocks:["Doom vs Avengers"],next:"Ultimate Spider-Man — Doomed",runtime:22},
{id:"ultimateDoom",title:"Ultimate Spider-Man — Doomed",year:"2012–2017",type:"episode",route:"Animation",priority:3,icon:"🕷️",theme:"b",poster:"assets/posters/20.jpg",source:"https://en.wikipedia.org/wiki/Ultimate_Spider-Man_(TV_series)",why:"Añade otra interpretación animada de Doom y refuerza la idea de que su amenaza puede cruzar equipos y universos.",before:["Spider-Man — Secret Wars recomendado"],learn:["Doom y Spider-Man","Villano recurrente","Tecnología","Multiverso"],connections:["Doom","Spider-Man","Animation"],unlocks:["Doom y Spider-Man"],next:"Avengers Assemble — Doctor Doom",runtime:22},
{id:"assembleDoom",title:"Avengers Assemble — Doctor Doom",year:"2013–2019",type:"series",route:"Avengers",priority:3,icon:"🛡️",theme:"r",poster:"assets/posters/21.webp",source:"https://en.wikipedia.org/wiki/Avengers_Assemble_(TV_series)",why:"Amplía las apariciones de Doom frente a los Avengers y permite reconocer patrones recurrentes de su estrategia.",before:["Avengers: Earth's Mightiest Heroes"],learn:["Doom vs Avengers","Estrategia","Doombots","Escala de amenaza"],connections:["Doom","Avengers","Doombots"],unlocks:["Doom multiequipo"],next:"Hulk and the Agents of S.M.A.S.H. — Doctor Doom",runtime:44},
{id:"smashDoom",title:"Hulk and the Agents of S.M.A.S.H. — Doctor Doom",year:"2013–2015",type:"episode",route:"Animation",priority:3,icon:"💥",theme:"g",poster:"assets/posters/22.jpg",source:"https://en.wikipedia.org/wiki/Hulk_and_the_Agents_of_S.M.A.S.H.",why:"Otra lectura de Doom como amenaza tecnológica y estratégica, ahora frente a un grupo de héroes.",before:["Doom como amenaza tecnológica"],learn:["Doom vs Hulk","Doombots","Estrategia","Equipo de héroes"],connections:["Doom","Hulk","Doombots"],unlocks:["Doom vs equipos"],next:"X-Men '97 — Doctor Doom",runtime:22},
{id:"x97Doom",title:"X-Men '97 — Doctor Doom",year:"2024–",type:"series",route:"Mutants",priority:4,icon:"✖️",theme:"p",poster:"assets/posters/23.jpg",source:"https://en.wikipedia.org/wiki/X-Men_%2797",why:"Añade el componente mutante al archivo y amplía el contexto de Doom dentro del panorama Marvel contemporáneo.",before:["X-Men recomendado"],learn:["Doom y mutantes","Marvel Animation","Continuidad moderna"],connections:["Doom","X-Men","Marvel Animation"],unlocks:["Doom y mutantes"],next:"Victor von Doom — Core Dossier",runtime:22},
{id:"doomCore",title:"Doctor Doom — VICTOR VON DOOM: CORE DOSSIER",year:"INTELLIGENCE FILE",type:"dossier",route:"Victor von Doom",priority:5,icon:"☠️",theme:"r",poster:"assets/posters/24.jpg",source:"https://www.marvel.com/characters/doctor-doom-victor-von-doom",why:"Expediente central para consolidar lo aprendido sobre Victor: identidad, ciencia, magia, Latveria, Doombots, Reed Richards, poder cósmico y multiverso.",before:["Completar varios expedientes de Doom"],learn:["Identidad de Victor","Latveria","Ciencia","Magia","Doombots","Reed Richards","Poder cósmico","Multiverso"],connections:["Victor von Doom","Latveria","Reed Richards","Doombots","Magic","Multiverse"],unlocks:["CORE DOSSIER","Victor von Doom"],next:"DOOMSDAY — FINAL BRIEFING",runtime:0}

];
const concepts=["Victor von Doom","Victor clásico","Reed Richards","Latveria","Fantastic Four","Historia de Victor","Doombots","Poder cósmico","Beyonder","Battleworld","Secret Wars","Poder absoluto","Multiverse","Incursions","Avengers","Variants","X-Men","Doom vs Hulk","Doom vs Iron Man","Doom vs Avengers","Doom en animación","Doom y mutantes","CORE DOSSIER"];
const cats={Doom:["Victor von Doom","Latveria","Doombots","Poder cósmico","Historia de Victor"],"Fantastic Four":["Fantastic Four","Reed Richards"],Avengers:["Avengers"],Multiverse:["Multiverse","Incursions","Variants"],"Secret Wars":["Beyonder","Battleworld","Secret Wars"]};
let state=JSON.parse(localStorage.getItem("doomSagaV5")||localStorage.getItem("doomSagaV4")||localStorage.getItem("doomSagaV3")||"{}");
let filter="all", currentView="map", spoilers=false;
function isDone(x){return !!state[x.id]}
function watchPct(){return Math.round(data.filter(isDone).length/data.length*100)}
function knowledgePct(){return Math.round(concepts.filter(c=>data.some(x=>isDone(x)&&x.unlocks.includes(c))).length/concepts.length*100)}
function threatLevel(k){return k>=90?"DOOM":k>=70?"MULTIVERSAL":k>=45?"EXTREME":k>=20?"HIGH":"UNKNOWN"}
function rank(p){return p>=100?"SECRET WARS MASTER":p>=80?"DOOMSDAY READY":p>=60?"BATTLEWORLD READY":p>=40?"MULTIVERSE AWARE":p>=20?"LATVERIA OPERATIVE":"DOOM INITIATE"}
function available(x){if(isDone(x))return true;let i=data.indexOf(x);return i<3||data.slice(0,i).some(isDone)}
function save(){localStorage.setItem("doomSagaV5",JSON.stringify(state))}
function render(){
let w=watchPct(),k=knowledgePct(),t=threatLevel(k),d=data.filter(isDone).length;
document.getElementById("seen").textContent=d+"/"+data.length;document.getElementById("watch").textContent=w+"%";document.getElementById("knowledge").textContent=k+"%";document.getElementById("threatTop").textContent=t;document.getElementById("rank").textContent=rank(w);document.getElementById("mainBar").style.width=w+"%";
document.getElementById("watchSide").textContent=w+"%";document.getElementById("watchBar").style.width=w+"%";document.getElementById("knowSide").textContent=k+"%";document.getElementById("knowBar").style.width=k+"%";document.getElementById("conceptCount").textContent=concepts.filter(c=>data.some(x=>isDone(x)&&x.unlocks.includes(c))).length+"/"+concepts.length;document.getElementById("threatSide").textContent=t;
let title=w===0?"BEGIN THE|INVESTIGATION":w<20?"THE INVESTIGATION|HAS BEGUN":w<40?"THE THREAT|IS EMERGING":w<70?"THE MULTIVERSE|IS UNSTABLE":w<100?"DOOMSDAY|IS APPROACHING":"YOU ARE|DOOMSDAY READY";let parts=title.split("|");document.getElementById("heroTitle").innerHTML=parts[0]+"<br><span>"+parts[1]+"</span>";document.getElementById("heroEyebrow").textContent=w===100?"ALL INTELLIGENCE UNLOCKED":"KNOW DOOM · UNLOCK THE MULTIVERSE · BE READY";
renderMap();renderLibrary();renderTimeline();renderDossier(k);renderJourney(w,k);renderMission();renderBadges(d,w,k)
}
function imageTag(x,cls=""){return x.poster?`<img class="${cls}" src="${x.poster}" alt="${x.title}" loading="lazy" onerror="this.remove()">`:""}
function renderMap(){
const coords=[
[3,14],[23,14],[43,14],[63,14],[83,14],
[83,33],[63,33],[43,33],[23,33],[3,33],
[3,52],[23,52],[43,52],[63,52],[83,52],
[83,71],[63,71],[43,71],[23,71],[3,71],
[3,87],[23,87],[43,87],[63,87],[83,87]
];
let h='<div class="grid"></div><div class="zone z1">🏰 LATVERIA</div><div class="zone z2">4️⃣ FANTASTIC FOUR</div><div class="zone z3">⚔️ AVENGERS</div><div class="zone z4">🌌 MULTIVERSE</div><div class="zone z5">🌀 BATTLEWORLD</div><div class="zone z6">☠️ DOOM DOSSIER</div>';
for(let i=0;i<data.length-1;i++){
 let a=coords[i],b=coords[i+1],dx=b[0]-a[0],dy=b[1]-a[1],len=Math.sqrt(dx*dx+dy*dy),ang=Math.atan2(dy,dx)*180/Math.PI;
 h+=`<div class="line ${isDone(data[i])?"on":""}" style="left:${a[0]+6}%;top:${a[1]+4}%;width:${len}%;transform:rotate(${ang}deg)"></div>`;
}
data.forEach((x,i)=>{
 let c=coords[i]||[50,50],locked=!available(x);
 h+=`<div class="node ${isDone(x)?"done":""} ${locked?"lock":""}" style="left:${c[0]}%;top:${c[1]}%" onclick="openItem('${x.id}')"><div class="thumb">${x.poster?imageTag(x):x.icon}</div><b>${i+1}. ${x.title}</b><small>${isDone(x)?"✓ COMPLETED":locked?"🔒 LOCKED":"🟢 AVAILABLE"}</small></div>`;
});
document.getElementById("mapCanvas").innerHTML=h;
}
function renderLibrary(){
let q=(document.getElementById("search")?.value||"").toLowerCase();
let shown=data.filter(x=>{let f=filter==="all"||filter==="movie"&&x.type==="movie"||filter==="series"&&x.type==="series"||filter==="episode"&&x.type==="episode"||filter==="must"&&x.priority===5||filter==="pending"&&!isDone(x)||filter==="done"&&isDone(x);let hay=(x.title+" "+x.route+" "+x.learn.join(" ")+" "+x.connections.join(" ")).toLowerCase();return f&&hay.includes(q)});
document.getElementById("filters").innerHTML=[["all","TODOS"],["movie","PELÍCULAS"],["series","SERIES"],["episode","EPISODIOS"],["must","IMPRESCINDIBLES"],["pending","PENDIENTES"],["done","VISTOS"]].map(a=>`<button class="${filter===a[0]?"active":""}" onclick="filter='${a[0]}';renderLibrary()">${a[1]}</button>`).join("");
document.getElementById("cards").innerHTML=shown.map(x=>`<article class="card ${isDone(x)?"done":""}" onclick="openItem('${x.id}')"><div class="poster ${x.theme}">${imageTag(x)}${x.poster?"":"<div class='fallback'>"+x.icon+"</div>"}<div class="pt"><small>${x.year} · ${x.route}</small><strong>${x.title}</strong></div></div><div class="body"><div class="chips"><span class="chip star">${"★".repeat(x.priority)}${"☆".repeat(5-x.priority)}</span><span class="chip">${x.type==="movie"?"PELÍCULA":x.type==="series"?"SERIE":"EPISODIO"}</span></div><div class="learn"><b>¿QUÉ DEBES APRENDER?</b><p>${x.learn.slice(0,3).join(" · ")}</p></div><div class="actions"><button onclick="event.stopPropagation();openItem('${x.id}')">VER EXPEDIENTE</button><button onclick="event.stopPropagation();toggle('${x.id}')">${isDone(x)?"✓ VISTO":"MARCAR VISTO"}</button></div></div></article>`).join("")||"<p style='font-size:11px;color:#89958d'>No hay resultados.</p>"
}
function renderTimeline(){document.getElementById("timelineTrack").innerHTML=data.map((x,i)=>`<div class="tl"><b>${i+1}. ${x.title}</b><small>${x.year} · ${x.route} · ${x.priority===5?"IMPRESCINDIBLE":"RECOMENDADO"}</small></div>`).join("")}
function renderDossier(k){
let fields=[["IDENTIDAD","Victor von Doom",k>0],["TÍTULO","Doctor Doom",k>0],["TERRITORIO","Latveria",k>=20],["RIVAL","Reed Richards",k>=15],["ESPECIALIDAD","Science / Technology / Strategy",k>=20],["PODER CÓSMICO",k>=45?"IDENTIFICADO":"UNKNOWN",k>=20],["BATTLEWORLD",k>=55?"IDENTIFICADO":"UNKNOWN",k>=45],["AMENAZA",threatLevel(k),k>=20]];
document.getElementById("fields").innerHTML=fields.map(f=>`<div class="field"><b>${f[0]}</b><span>${f[2]?f[1]:"🔒 Información clasificada"}</span></div>`).join("");document.getElementById("threat").textContent=threatLevel(k);document.getElementById("threatBar").style.width=Math.min(100,k)+"%";document.getElementById("network").innerHTML=concepts.map((c,i)=>{let on=data.some(x=>isDone(x)&&x.unlocks.includes(c));return `<span class="concept ${on?"on":""}">${on?"🔓":"🔒"} ${c}</span>`}).join("")
}
function renderJourney(w,k){
let d=data.filter(isDone).length,hrs=data.filter(isDone).reduce((a,x)=>a+x.runtime,0)/60;let cards=[["WATCH",""+w+"%","Contenido completado"],["KNOWLEDGE",""+k+"%","Conceptos desbloqueados"],["RUNTIME",hrs.toFixed(1)+" h","Tiempo visto estimado"],["RANK",rank(w),"Nivel de campaña"],["MOVIES",data.filter(x=>x.type==="movie"&&isDone(x)).length,"Películas vistas"],["EPISODES",data.filter(x=>x.type==="episode"&&isDone(x)).length,"Episodios vistos"],["BADGES",document.querySelectorAll(".badge.on").length,"Insignias desbloqueadas"],["NEXT",data.find(x=>!isDone(x))?.title||"COMPLETE","Siguiente misión"]];document.getElementById("journeyGrid").innerHTML=cards.map(c=>`<div class="journeyCard"><b>${c[0]}</b><strong>${c[1]}</strong><span>${c[2]}</span></div>`).join("");
document.getElementById("knowledgeCats").innerHTML=Object.entries(cats).map(([name,list])=>{let got=list.filter(c=>data.some(x=>isDone(x)&&x.unlocks.includes(c))).length;return `<div class="journeyCard"><b>${name.toUpperCase()}</b><strong>${Math.round(got/list.length*100)}%</strong><span>${got}/${list.length} conceptos</span></div>`}).join("")
}
function renderMission(){let x=data.find(x=>!isDone(x));document.getElementById("mission").textContent=x?x.title:"DOOM SAGA COMPLETE";document.getElementById("missionText").textContent=x?x.why:"Has completado el archivo. All intelligence unlocked."; }
function renderBadges(d,w,k){let b=[["🏰","LATVERIA DISCOVERED",k>=20],["🧠","DOOM'S INTELLECT",k>=30],["⚔️","DOOM VS AVENGERS",d>=6],["🌌","MULTIVERSE AWARE",k>=45],["🌀","BATTLEWORLD READY",k>=60],["💀","DOOMSDAY READY",w>=80],["🏆","SECRET WARS MASTER",w>=100]];document.getElementById("badges").innerHTML=b.map(x=>`<div class="badge ${x[2]?"on":""}" style="border:1px solid ${x[2]?"#4da657":"#293d2d"};border-radius:10px;padding:9px;text-align:center;color:${x[2]?"#daf8dd":"#6e7870"};font-size:8px;background:${x[2]?"#0d1c10":"#080d09"}"><div style="font-size:19px">${x[0]}</div>${x[1]}</div>`).join("")}
function openItem(id){let x=data.find(x=>x.id===id);let hero=`<div class="modalTitle"><div class="eyebrow">${x.route.toUpperCase()}</div><h2>${x.title}</h2><div style="font-size:9px;color:#b4c0b6">${x.year} · ${x.type.toUpperCase()} · ${"★".repeat(x.priority)}${"☆".repeat(5-x.priority)}</div></div>`;document.getElementById("modalHero").innerHTML=(x.poster?imageTag(x):"")+hero;document.getElementById("modalContent").innerHTML=`<h3>🎯 ¿POR QUÉ DEBES VER ESTO?</h3><p>${x.why}</p><h3>⚠️ ANTES DE VER</h3><ul>${x.before.map(v=>`<li>${v}</li>`).join("")}</ul><h3>🧠 QUÉ DEBES APRENDER</h3><ul>${x.learn.map(v=>`<li>${v}</li>`).join("")}</ul><h3>🔗 CONEXIONES</h3><div class="chips">${x.connections.map(v=>`<span class="chip">${v}</span>`).join("")}</div><h3>🔥 DESPUÉS DE VER</h3><p>Ahora debes poder reconocer: ${x.learn.slice(0,3).join(", ")}.</p><p><b>Siguiente misión:</b> ${x.next||"Archivo completado"}</p><h3>🔓 DESBLOQUEA</h3><div class="unlock">${x.unlocks.length?x.unlocks.join(" · "):"Refuerza conocimientos existentes."}</div><div class="source">🟢 Poster local integrado en V5.1 · Imagen / referencia: <a href="${x.source}" target="_blank" rel="noopener">ver fuente</a></div><div class="modalBtns"><button onclick="toggle('${x.id}');closeModal()">${isDone(x)?"✓ MARCADO COMO VISTO":"☐ MARCAR COMO VISTO"}</button><button onclick="closeModal()">CERRAR EXPEDIENTE</button></div>`;document.getElementById("modal").classList.add("open")}
function closeModal(){document.getElementById("modal").classList.remove("open")}
function toggle(id){if(state[id])delete state[id];else state[id]=true;save();render()}
function continueMission(){let x=data.find(x=>!isDone(x));if(x)openItem(x.id)}
function marathon(p){let a=p?data.filter(x=>x.priority>=p):data,h=a.reduce((s,x)=>s+x.runtime,0)/60,done=a.filter(isDone).length;document.getElementById("marathonResult").innerHTML=`<b>${a.length} contenidos</b> · duración estimada <b>${h.toFixed(1)} h</b> · progreso <b>${done}/${a.length}</b>.`}
function toggleSpoiler(){spoilers=!spoilers;document.getElementById("spoilerText").style.display=spoilers?"block":"none"}
function switchView(v){currentView=v;document.querySelectorAll(".view").forEach(e=>e.classList.remove("active"));document.getElementById(v).classList.add("active");document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));if(v==="library")renderLibrary()}
document.getElementById("nav").addEventListener("click",e=>{if(e.target.tagName==="BUTTON")switchView(e.target.dataset.view)});
document.getElementById("bottomNav").addEventListener("click",e=>{if(e.target.closest("button"))switchView(e.target.closest("button").dataset.view)});
document.getElementById("search").addEventListener("input",renderLibrary);
document.getElementById("modal").addEventListener("click",e=>{if(e.target.id==="modal")closeModal()});
function countdown(){let t=new Date("2026-12-18T00:00:00"),d=Math.max(0,Math.ceil((t-new Date())/86400000));document.getElementById("days").textContent=d}
countdown();setInterval(countdown,3600000);render();
